### ISSUE TITLE
Problem starting using compose

### ISSUE THREAD

**Issue by fzipi** [microsoft/waflab#30]
Trying to get this working, but fails on docker compose up:

```
❯ docker compose up
[+] Running 2/0
 ⠿ Container waflab_frontend_1  Created                                                                           0.0s
 ⠿ Container waflab_backend_1   Created                                                                           0.0s
Attaching to backend_1, frontend_1
backend_1   | {"status":"Pulling from waflab/wafbench","id":"latest"}
backend_1   | {"status":"Digest: sha256:1e94302e53cee0e390b2b7a13fb28f971fa39ac99f9a9b0a0d7a9fef7e0520c0"}
backend_1   | {"status":"Status: Image is up to date for waflab/wafbench:latest"}
backend_1   | panic: Error response from daemon: container cannot be disconnected from host network or connected to host network
backend_1   |
backend_1   | goroutine 1 [running]:
backend_1   | github.com/waflab/waflab/docker.MakeMaster(0x5, 0x200000003)
backend_1   | 	/go/src/app/docker/master.go:134 +0x410
backend_1   | github.com/waflab/waflab/object.InitMaster(...)
backend_1   | 	/go/src/app/object/run.go:18
backend_1   | main.main()
backend_1   | 	/go/src/app/main.go:15 +0x34
backend_1 exited with code 2
```

Is something additionally required?

**Comment by hsluoyz** [comment]
@Olament

**Comment by enceladus3** [comment]
Getting the same error.

**Comment by fzipi** [comment]
This is still happening.

**Comment by fzipi** [comment]
I get more progress after doing some changes to the go files, but still
```
❯ docker-compose up
[+] Running 2/3
 ⠿ Container waflab-frontend-1                                        Created                                                                                           0.0s
 ⠿ Container waflab-backend-1                                         Recreated                                                                                         1.5s
 ⠹ backend Published ports are discarded when using host network mode                                                                                                   0.0s
Attaching to waflab-backend-1, waflab-frontend-1
waflab-backend-1   | Enumerating objects: 24486, done.
Counting objects: 100% (116/116), done.  0% (1/116)
Compressing objects: 100% (76/76), done.:   1% (1/76)
waflab-backend-1   | Total 24486 (delta 62), reused 84 (delta 40), pack-reused 24370
waflab-backend-1   | Enumerating objects: 2721, done.
Counting objects: 100% (1328/1328), done.0% (1/1328)
Compressing objects: 100% (393/393), done.  0% (1/393)
waflab-backend-1   | Total 2721 (delta 838), reused 1299 (delta 824), pack-reused 1393
waflab-backend-1   | docker/master: failed to initialize Docker client
waflab-backend-1   | Do you have Docker (https://www.docker.com/) installed?
waflab-backend-1   | panic: dial tcp [::1]:3306: connect: connection refused
waflab-backend-1   |
waflab-backend-1   | goroutine 1 [running]:
waflab-backend-1   | github.com/waflab/waflab/object.(*OrmManager).open(0xc001bdc390)
waflab-backend-1   | 	/go/src/app/object/orm_manager.go:63 +0x13c
waflab-backend-1   | github.com/waflab/waflab/object.NewOrmManager(0xe83870, 0x5, 0xc0000dce80, 0x1d, 0x1d)
waflab-backend-1   | 	/go/src/app/object/orm_manager.go:42 +0x7d
waflab-backend-1   | github.com/waflab/waflab/object.InitOrmManager()
waflab-backend-1   | 	/go/src/app/object/orm_manager.go:17 +0x73
waflab-backend-1   | main.main()
waflab-backend-1   | 	/go/src/app/main.go:16 +0x52
waflab-backend-1 exited with code 2
```
