### ISSUE TITLE
waflab generate panics generating tests

### ISSUE THREAD

**Issue by fzipi** [microsoft/waflab#31]
Hi Team!

Cannot get waflab generate to work. After building the container, generate panics:

```
root@docker-desktop:/go/src/app# waflab generate repos/coreruleset/rules/ repos/coreruleset/tests/regression/ -c 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xbbc209]

goroutine 1 [running]:
github.com/waflab/waflab/cmd/command.generateTestfile.func1(0x0, 0x0, 0x0, 0x0, 0xe66c20, 0xc00036d380, 0x2, 0x2)
	/go/src/app/cmd/command/utils.go:21 +0x49
path/filepath.Walk(0x0, 0x0, 0xc00035fc70, 0x32, 0x135e840)
	/usr/local/go/src/path/filepath/path.go:499 +0x7e
github.com/waflab/waflab/cmd/command.generateTestfile(0x0, 0x0, 0x1, 0x3, 0x3, 0x2, 0xc00000f980, 0xc00035fd58)
	/go/src/app/cmd/command/utils.go:20 +0x85
github.com/waflab/waflab/cmd/command.generate(0x1320c60, 0xc0003a0e80, 0x2, 0x4)
	/go/src/app/cmd/command/generate.go:37 +0x9a
github.com/spf13/cobra.(*Command).execute(0x1320c60, 0xc0003a0e40, 0x4, 0x4, 0x1320c60, 0xc0003a0e40)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1320ee0, 0xc00035ff58, 0x2, 0x2)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/waflab/waflab/cmd/command.Execute()
	/go/src/app/cmd/command/root.go:35 +0x7d
main.main()
	/go/src/app/cmd/main.go:6 +0x25
```

**Comment by enceladus3** [comment]
@fzipi  any luck fixing this or  "Problem starting using compose #30" issue? 
https://github.com/microsoft/waflab/issues/30

**Comment by fzipi** [comment]
Didn't tried again, but I can give it another shot tomorrow.
